### ISSUE TITLE
More Emulators?

### ISSUE THREAD

**Issue by Haris1977** [digitalLumberjack/recalbox-os#342] opened 2015-08-14 14:31 UTC
Any thoughts about adding new emulators like

AMIGA (uae4all), C64 (vice), TYRQUAKE, PRBOOM, DOUKUTSU, DINOTHAWR??

This would be great:)

**Comment by Guzilli** [comment] 2015-08-18 18:02
Amiga and C64 would really be epic. Love those systems

**Comment by lordtaki** [comment] 2015-08-24 12:06
Looks like a duplicate of https://github.com/digitalLumberjack/recalbox-os/issues/190 ?

**Comment by kryptto** [comment] 2015-10-12 13:10
Intellivision +

**Closed** 2015-10-12 17:22 UTC
