### ISSUE TITLE
PS1 emulator : Xbox360 controller not well recognized

### ISSUE THREAD

**Issue by NerosTie** [digitalLumberjack/recalbox-os#117] opened 2015-03-06 16:02 UTC
On a Raspberry Pi 2 with the PS1 emulator, the Xbox360 controller is not well mapped.
Buttons are reversed:
A<->B
X<->Y

L2, R2 are not working.

Tested with Metal Gear Solid - PAL.

**Comment by digitalLumberjack** [comment] 2015-03-06 16:44
Yes need the xboxdrv available soon to manage L2 and R2 as buttons...
Are A<->B and X<->Y reversed in other platforms ?
Did you configure the controller yourself or did you use it out of the box ?

**Comment by Energizing** [comment] 2015-03-06 17:05
A<->B and X<->Y are not reversed the buttons are just set to be like the playstation controller, at least on my raspberry... maybe you changed something in the settings?

**Comment by NerosTie** [comment] 2015-03-06 17:19
@digitalLumberjack I thought the xboxdrv was in recalboxOS v3.2.5 ( "xboxdrv binary" )
Not sure if it's reversed in other platforms (tested with a game on gbc and megadrive, seems good)
Tested both out of the box and then I configured myself because the hotkey was not mapped.

@Energizing I don't think. Because if it's good with the emulationstation menu, it's reversed in the PS1 emulator. But if it's good in the PS1 emulator, it's reversed with emulationstation...

I really think it's RetroArch, because it's fine with EmulationStation.

**Comment by Energizing** [comment] 2015-03-06 17:23
anyway it's easy to change, retroarch > settings > input settings user 1

i'm using a wireless 360 controller so maybe it's only a wired controller problem

**Comment by NerosTie** [comment] 2015-03-06 17:28
@Energizing I will do that.
But R2 & L2 is more problematic.

**Comment by Energizing** [comment] 2015-03-06 17:29
yeah it's going to be in the next update i think, or pretty soon after that!

**Comment by digitalLumberjack** [comment] 2015-03-06 21:23
The xboxdrv binary is available since 3.2.5 but you should load it
manually. 3.2.8 will allow you to configure it through recalbox.conf

**Comment by iMaster29** [comment] 2015-03-07 22:34
Just a message to say that I've been through the same problem: wrong mapped buttons in ps1 emulator with a wired xbox 360 controller. It looks confuse between snes controller and xbox controller.

**Comment by Energizing** [comment] 2015-03-07 22:53
just to be sure, you did put controls from emulationstation like on a Snes controller right? because X>Y and A>B are reversed on the X360 controller

![](http://ic.pics.livejournal.com/lady_eklipse/35501264/30385/original.jpg)

**Comment by NerosTie** [comment] 2015-03-07 23:05
@Energizing Yes. If Emulationstation asks for A, we press A.
As i said, it works well on emulationstation (A to validate, B to return).
But, if we are aware of the inversion SNES/X360 and we press B for A, A for B, ... it's reversed in emulationstation, A to return and B to validate.

Very confusing :/

I think asking for A, for B, for Y, for X is not the best solution. 
The mapper should ask for "the button on top, the button on lef, the button on right, the button on bottom".
It's a better solution for most of the controllers.

**Comment by iMaster29** [comment] 2015-03-07 23:06
I pressed A on my xbox controller for A on emulationstation and so on for the other.
I played Gameboy games and the buttons were not swap.
Also in emulationstation A is for confirm and B is to go back as traditional so it's accurate with my inputs.

**Comment by Energizing** [comment] 2015-03-07 23:22
well i put emulationstation controls like a snes controller, so on my x360 controller B = A / A = B / Y = X / X = Y and never had any problems, when i launch a nes/snes game it's like the original controller and on PSX emulator X is at the bottom, triangle at top, circle on the left and square on the right, like a real PSX controller, don't know what went wrong for you

**Comment by NerosTie** [comment] 2015-03-07 23:29
@Energizing Yes, but reversed in emulationstation. A to go back, B to validate.
And still, it will be confusing for everyone installing RecalBox.

**Comment by iMaster29** [comment] 2015-03-07 23:29
I didn't try snes games but It's hard to me to confirm with the B button on the 360 controller.
Reminds me the fact that on Playstation Cross and Circle were swapped for confirm between Japan and some other countries in the world.

**Comment by NerosTie** [comment] 2015-03-07 23:34
@iMaster29 I'm playing with Metal Gear Solid - PAL and Crash Team Racing - PAL.
I'm reeeeally sure it's reversed :)
(MGS it's O to confirm, X to go back and in CTR it's X to confirm, O to go back).

**Comment by iMaster29** [comment] 2015-03-07 23:45
@NerosTie I agreed. I spoke about the Playstation story just to show that this "confirm" thing just add confusion to the confusion even on one system there were not able to make a standard for the all world.

We all know that snes and xbox have buttons swapped. Just that with an xbox controller it's really strange to confirm with B. That's why I don't want just to press the buttons snes style in emulationstation.

Also in Gameboy it seems to me that there were not swap so I think that there is something to do to align all the systems.

**Comment by NerosTie** [comment] 2015-03-07 23:49
@iMaster29 Let's see what will happen with xboxdrv first. L2/R2 is more important.
But it's strange, on PC (retroarch+emulationstation too), I don't need for a xboxdrv and L2/R2 are recognized in emulationstation.

**Comment by Energizing** [comment] 2015-03-08 00:05
well i just configured my emulationstation controls without looking at my x360's buttons and put it like the snes one, no problems on any emulator after that, i figured this was the way they wanted it to be, or maybe it's just random for each king of controllers, didn't try anything else so i wouldnt know

**Comment by iMaster29** [comment] 2015-03-08 00:54
I think I said something wrong about the Gameboy emulator. Button A match my A because I configured it in the menu but is on the bottom of the controller and not on the right like on a real Gameboy.

Guess I may have to go with B has confirm. I can't believe I say that.

**Comment by Energizing** [comment] 2015-03-08 01:02
so emulationstation is clearly based on snes-like controls, that's why you feel like everything is mixed up! ahah

**Comment by NerosTie** [comment] 2015-03-08 01:06
So, should it be reversed in emulationstation instead?
@Energizing: it should be more generic.

**Comment by Energizing** [comment] 2015-03-08 01:14
well every controller is different, this way if you configure it like a snes controller you're good to go with every emulators, except if you're missing buttons like a NES controller etc... but i suppose (hope) people with NES controllers won't try to play PSX with it...

**Comment by Energizing** [comment] 2015-03-08 01:24
if we were to replace emulationstation control names, for exemple: "A" to "Confirm" and "B" to "Cancel/Go Back" then people would always put a different button based on what they're used to, and then this would mix things up in the emulators, but with a Snes-like configuration they would automatically get everything set up as the real console controls, and if they really don't like it they can still change it in the frontend then in retroarch!

**Comment by NerosTie** [comment] 2015-03-08 01:34
If we replace with "upper button", " left button", "right button"... it's a great solution to me!
(It's the solution of retroarch btw)

A newbe can't know that B means SNES-B...
It should be simple for everyone.

**Comment by Energizing** [comment] 2015-03-08 01:42
could be mixed up with D-pad, but something like that would be nice

i never noticed that in retroarch, when i change PSX controls it always says cross button, square button, etc, and in SNES i get A, B etc... how did you get this? or did you mean retropie?

**Comment by digitalLumberjack** [comment] 2015-03-08 07:12
Yep so as it is written on the manual, https://github.com/digitalLumberjack/recalbox-os/wiki/Manual-%28EN%29#3---add-an-usb-controller
The buttons are named after snes controller.
As it is written on the manual, https://github.com/digitalLumberjack/recalbox-os/wiki/Manual-%28EN%29#iii---emulationstation A is for selection and B for back. As on old school games controllers.

What i need to know is if the default configuration of xbox pad in recalbox is swapped, because i did not do it and i have not tested it. @Energizing ?

**Comment by Energizing** [comment] 2015-03-08 10:48
no it's just that X360 controllers have A/B/X/Y too except A-B and X-Y are reversed, and Neros and iMaster put A on xbox A and B on xbox B etc... which means reversed snes controls, but i put them like a snes controller and never had any problem!

**Comment by iMaster29** [comment] 2015-03-08 13:39
I never owned a snes which us right (A) button to confirm.
I have a ps1, ps2, ps3, xbox, xbox360 and they all use the bottom (cross or A) button to confirm.

With the xbox360 controller well configured as a snes controller, I have to use the left (B on 360) button to confirm in navigation menu.

I think I will have to adapt or die.

**Comment by NerosTie** [comment] 2015-03-08 13:43
Le dimanche 8 mars 2015, 06:39:13 iMaster29 a �crit :
> I never owned a snes which us right (A) button to confirm.
> I have a ps1, ps2, ps3, xbox, xbox360 and they all use the bottom (cross or
> A) button to confirm.
> 
> With the xbox360 controller well configured as a snes controller, I have to
> use the left (B on 360) button to confirm in navigation menu.
> 
> I think I will have to adapt or die.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/digitalLumberjack/recalbox-os/issues/117#issuecomment-777
> 49343
I'm in the same case as @iMaster29.
For non-Nintendo players, this is confusing. A lot!

**Comment by digitalLumberjack** [comment] 2015-03-08 15:03
But i always used circle to confirm, either on nintendo, on Final Fantasy
until 8, etc ... The X to accept has been integrated to games by evil
people ! :P

**Comment by iMaster29** [comment] 2015-03-08 16:11
In Europe on playstation: Cross is confirm, Circle is back.
In Japan on playstation: Circle is confirm, Cross is back

but some Japanese games (like MGS or Final Fantasy) keep Circle as confirm and Cross as back when they were released in Europe.

**Comment by digitalLumberjack** [comment] 2015-03-08 16:21
I know, that can be as weird as driving on left side of the road when you go to england... :)

**Comment by iMaster29** [comment] 2015-03-08 16:24
or Japan.

**Comment by NerosTie** [comment] 2015-03-14 03:14
@digitalLumberjack In 3.2.8, the mapping of the x360 controller is still terrible.
  * x360 mapping is no autoselected. I have to map manually
  * In a PS1 game, square gives "square+L2". I have to put L2 and R2 to nothing in emulationstation configuration.
  * A pure configuration with RetroArch works perfectly! But I lost the config if I restart.
  * In the configuration file of x360 controller, there are many errors (ex: L2&R2 are not buttons but axis!)

Here my file:

```
input_device = "Microsoft X-Box 360 pad"
input_driver = "udev"
input_menu_toggle_btn = 0
input_state_slot_decrease_btn = h0down
input_left_btn = h0left
input_rewind_btn = h0left
input_screenshot_btn = 4
input_right_btn = h0right
input_hold_fast_forward_btn = h0right
input_exit_emulator_btn = 7
input_up_btn = h0up
input_state_slot_increase_btn = h0up
input_load_state_btn = 3
input_save_state_btn = 2

input_b = "z"
input_b_btn = "0"
input_y = "a"
input_y_btn = "2"
input_select = "rshift"
input_select_btn = "6"
input_start = "enter"
input_start_btn = "7"
input_up = "up"
input_up_btn = "h0up"
input_up_axis = "nul"
input_down = "down"
input_down_btn = "h0down"
input_left = "left"
input_left_btn = "h0left"
input_left_axis = "nul"
input_right = "right"
input_right_btn = "h0right"
input_a = "x"
input_a_btn = "1"
input_x = "s"
input_x_btn = "3"
input_l = "q"
input_l_btn = "4"
input_r = "w"
input_r_btn = "5"
input_l2_axis = "+2"
input_r2_axis = "+5"
input_l3_btn = "9"
input_r3_btn = "10"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"
input_r_y_plus_axis = "+4"
input_r_y_minus_axis = "-4"
```

**Comment by NerosTie** [comment] 2015-03-14 14:55
It works with xboxdrv set to 1 in recalbox.conf (https://github.com/digitalLumberjack/recalbox-os/wiki/recalbox.conf-%28EN%29).
Activated by default could be great!
Left joystick no activated by default, have to do it in retroarch configuration.

**Closed** 2015-03-16 10:31 UTC

**Comment by julianxhokaxhiu** [comment] 2015-12-14 07:47
Sorry to disappoint you but I actually found that the issue is still there. Yesterday I was going to play a PSX game and I found that buttons are still swapped ( X => B and O => A ).

Mapping of course is done correctly ( A => A ) on my Pad ( http://www.speedlink.com/?p=2&cat=4131&pid=38925&paus=1 ) which is a xboxdrv compatible pad. I enabled the flag ( L2 and R2 are seen as buttons ) and I disabled the one for PS3 support.

What am I supposed to do to fix my issue?

**Comment by digitalLumberjack** [comment] 2015-12-14 08:09
@julianxhokaxhiu https://github.com/recalbox/recalbox-os/wiki/Manual-%28EN%29#xboxcontrollers
Mapping of course is done correctly ( A => A ) -> did you read the issue and the wiki ?

**Comment by julianxhokaxhiu** [comment] 2015-12-14 08:13
Ah ok, so since the mapping is done based on a SNES controller, should I assign my B pad button to the A snes button? So doing this I'll get the A => X right?

I saw the wiki but I thought It was just for a reference. And that the "swapping" logic was done in the configuration later of retroarch from the system.
